name: first_workflow

on:
  push:
    branches:
      - main

jobs:
  job_01:
    runs-on: ubuntu-latest

    steps:
      - name: print a welcome message
        run: echo "Hello"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: list all files
        run: ls -la
