name: Hybrid and Dockerized Jobs

on:
  workflow_dispatch:

jobs:
  hybrid_job:
    runs-on: ubuntu-latest
    name: Hybrid Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run directly on host
        run: echo "Running ${GITHUB_JOB} in ${{ github.event_name }} event"

      - name: Run inside Alpine container
        uses: docker://alpine:latest
        with:
          args: sh -c "echo 'Running inside an Alpine container'"

  dockerized_job:
    runs-on: ubuntu-latest
    container:
      image: node:20
      options: --init
    name: Dockerized Job
    steps:
      - name: Show Node version
        run: node --version

      - name: Run inside Node container
        run: echo "Running inside a Node.js container"
