on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy to'
          required: true
          default: 'staging'
          type: choice
          options:
            - staging
            - production
jobs:
    manual-deploy:
        runs-on: ubuntu-latest
        name: Manual Deployment
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to environment
              run: |
                echo "Deploying to ${{ github.event.inputs.environment }} environment..."
                # Add deployment commands here
                if [ "${{ github.event.inputs.environment }}" == "production" ]; then
                  echo "Running production deployment scripts..."
                else
                  echo "Running staging deployment scripts..."
                fi