on:
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"

jobs:
  run_js_app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: run test
        run: npm test
